config/routes.rb
Rails.application.routes.draw do
  resources :topics do
    member do
      post 'upvote'
      post 'downvote'
    end
  end  # The priority is based upon order of creation: first created -> highest priority.

  root 'topics#index'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
   has_many :votes, dependent: :destroy
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :topic, :counter_cache => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all.order("votes_count DESC, id DESC")
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to topics_path, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to topics_path, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @topic = Topic.find(params[:id])
    @topic.votes.create
    redirect_to(topics_path)
  end

  def downvote
    @topic = Topic.find(params[:id])
    if @topic.votes.count>0
      @topic.votes.last.destroy
      @topic.save
    end
    redirect_to(topics_path)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/common/_footer.html.erb
<footer class="footer">
  <div class="container">
    <p class="text-muted">Copyright © anxgang.suggestotron 2016</p>
  </div>
</footer>

app/views/common/_navbar.html.erb
<!-- Fixed navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Suggestotron", root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Home", root_path %></li>
        <li><a href="#about">About</a></li>
      </ul>
      <!--<ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li class="dropdown-header">Nav header</li>
            <li><a href="#">Separated link</a></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <div class="navbar-form navbar-right">
            <%= link_to "Sign Up", root_path, class: "btn btn-success" %>
      </div>-->
      </div>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Suggestotron</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'common/navbar' %>
<div class="container">
<%= yield %>
</div>
<%= render 'common/footer' %>
</body>
</html>

app/views/topics/_form.html.erb
<%= simple_form_for @topic do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.input :title, label: '主題' %>
    <%= f.input :description, label: '內容' %>
  </div>
  <%= f.submit "送出", class: "btn btn-primary pull-right", data: { disable_with: "submiting..." } %>
<% end %>

app/views/topics/edit.html.erb
<h1>編輯主題</h1>

<%= render 'form' %>

<%= link_to '返回', topics_path, class: 'btn btn-default' %>

app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>主題清單</h1>
<%= link_to '新增主題', new_topic_path, class: 'btn btn-primary pull-right' %>
<table class="table ">
  <thead>
    <tr>
      <th>標題</th>
      <th>投票數</th>
      <th>投票</th>
      <th>取消</th>
      <th>刪除</th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= link_to topic.title, topic_path(topic) %></td>
        <td><%= pluralize(topic.votes.size, "vote") %></td>
        <td><%= button_to '+1', upvote_topic_path(topic), class: 'btn btn-xs btn-default', method: :post %></td>
        <td><%= button_to '-1', downvote_topic_path(topic), class: 'btn btn-xs btn-default', method: :post %></td>
        <td><%= link_to 'Del', topic, class: 'btn btn-xs btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/topics/new.html.erb
<h1>新增主題</h1>

<%= render 'form' %>

<%= link_to '返回', topics_path, class: 'btn btn-default' %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>


  <strong>Title</strong>
  <%= @topic.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @topic.description %>
</p>

<%= link_to '編輯', edit_topic_path(@topic), class: 'btn btn-primary' %>
<%= link_to '返回', topics_path, class: 'btn btn-default' %>